/**
 * UI Component Registry — structured metadata for all known reusable components.
 * The engine queries this to select real components instead of hallucinating imports.
 */

export type ComponentCategory =
  | 'layout' | 'hero' | 'content' | 'interactive'
  | 'data' | 'navigation' | '3d' | 'motion' | 'feedback';

export interface ComponentEntry {
  name: string;
  exportName: string;
  category: ComponentCategory;
  subcategory?: string;
  description: string;
  compatibleLayouts: string[];
  compatibleStyles: string[];
  requiredLibraries: string[];
  dependencies: string[];
  previewSafe: boolean;
  animationSupport: boolean;
  threeDSupport: boolean;
  physicsSupport: boolean;
  responsive: boolean;
  usagePriority: number; // 1 = always use, 10 = rarely use
  intendedUsage: string;
  requiredProps: string[];
  optionalProps: string[];
}

export const COMPONENT_REGISTRY: ComponentEntry[] = [
  // ─── Layout Components ─────────────────────────────────────────────────────
  { name:'Sidebar',exportName:'Sidebar',category:'layout',subcategory:'navigation',description:'Vertical sidebar navigation with links, sections, icons, and collapse',compatibleLayouts:['dashboard','admin-panel','saas-product','sidebar-header-content','IDE-style'],compatibleStyles:['minimal','clean-corporate','premium-dark','monochrome'],requiredLibraries:['lucide-react'],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:2,intendedUsage:'Persistent app sidebar navigation',requiredProps:['links'],optionalProps:['collapsed','onCollapse','header','footer'] },
  { name:'Header',exportName:'Header',category:'layout',subcategory:'navigation',description:'Top app header with logo, navigation links, and action buttons',compatibleLayouts:['landing-page','dashboard','saas-product'],compatibleStyles:['minimal','clean-corporate','glassmorphism'],requiredLibraries:['lucide-react'],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:2,intendedUsage:'Top navigation bar for apps',requiredProps:[],optionalProps:['logo','links','actions','sticky'] },
  { name:'SplitPanel',exportName:'SplitPanel',category:'layout',subcategory:'container',description:'Resizable two-panel split layout',compatibleLayouts:['split-screen','IDE-style','saas-product'],compatibleStyles:['minimal','monochrome','premium-dark'],requiredLibraries:[],dependencies:[],previewSafe:true,animationSupport:false,threeDSupport:false,physicsSupport:false,responsive:false,usagePriority:5,intendedUsage:'Side-by-side editor/preview pane',requiredProps:['leftContent','rightContent'],optionalProps:['defaultSplit','direction'] },
  { name:'GridShell',exportName:'GridShell',category:'layout',subcategory:'container',description:'CSS grid container shell for responsive card layouts',compatibleLayouts:['dashboard','analytics','hero-features-cta'],compatibleStyles:['minimal','clean-corporate'],requiredLibraries:[],dependencies:[],previewSafe:true,animationSupport:false,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:3,intendedUsage:'Wrapping grid for metric/feature cards',requiredProps:['children'],optionalProps:['cols','gap'] },
  { name:'SectionWrapper',exportName:'SectionWrapper',category:'layout',subcategory:'container',description:'Full-width section container with max-width centering and padding',compatibleLayouts:['landing-page','blog','documentation'],compatibleStyles:['minimal','clean-corporate','editorial'],requiredLibraries:[],dependencies:[],previewSafe:true,animationSupport:false,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:3,intendedUsage:'Consistent section padding and centering',requiredProps:['children'],optionalProps:['maxWidth','background','id'] },
  { name:'BentoShell',exportName:'BentoShell',category:'layout',subcategory:'container',description:'Asymmetric bento grid layout shell',compatibleLayouts:['bento-grid','bento-layout','landing-page'],compatibleStyles:['minimal','saas-stripe','bento-grid'],requiredLibraries:[],dependencies:[],previewSafe:true,animationSupport:false,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:4,intendedUsage:'Bento-style feature layout grid',requiredProps:['children'],optionalProps:['gap','cols'] },

  // ─── Hero / Showcase Components ────────────────────────────────────────────
  { name:'HeroSection',exportName:'HeroSection',category:'hero',subcategory:'landing',description:'Full-width hero with headline, subtext, CTA button, and optional background',compatibleLayouts:['landing-page','portfolio','startup-website','hero-features-cta'],compatibleStyles:['minimal','saas-stripe','gradient-heavy','glassmorphism'],requiredLibraries:['lucide-react'],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:1,intendedUsage:'Primary landing page hero',requiredProps:['headline'],optionalProps:['subtext','cta','backgroundType','badge'] },
  { name:'AnimatedHero',exportName:'AnimatedHero',category:'hero',subcategory:'motion',description:'Hero section with entrance animations using framer-motion',compatibleLayouts:['landing-page','animated-ui','scroll-storytelling'],compatibleStyles:['gradient-heavy','premium-dark','futuristic'],requiredLibraries:['framer-motion','lucide-react'],dependencies:['HeroSection'],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:3,intendedUsage:'Animated marketing hero with reveal effects',requiredProps:['headline'],optionalProps:['subtext','cta','animationVariant'] },
  { name:'GradientHero',exportName:'GradientHero',category:'hero',subcategory:'visual',description:'Hero with rich gradient background, often with mesh or radial gradients',compatibleLayouts:['landing-page','startup-website'],compatibleStyles:['gradient-heavy','premium-dark','futuristic'],requiredLibraries:[],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:3,intendedUsage:'Visually rich hero background',requiredProps:['headline'],optionalProps:['gradientColors','cta'] },
  { name:'3DHeroScene',exportName:'HeroScene3D',category:'hero',subcategory:'3d',description:'Three.js / R3F 3D scene used as a hero section backdrop',compatibleLayouts:['3d-hero','webgl-ui'],compatibleStyles:['futuristic','premium-dark','glassmorphism'],requiredLibraries:['@react-three/fiber','@react-three/drei'],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:true,physicsSupport:false,responsive:true,usagePriority:6,intendedUsage:'3D background scene for hero sections',requiredProps:[],optionalProps:['ambientColor','rotationSpeed'] },
  { name:'CinematicHero',exportName:'CinematicHero',category:'hero',subcategory:'motion',description:'Full-screen cinematic hero with video or animated background',compatibleLayouts:['agency-website','portfolio','scroll-storytelling'],compatibleStyles:['editorial','luxury','premium-dark'],requiredLibraries:['framer-motion'],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:5,intendedUsage:'Cinematic first-impression hero',requiredProps:[],optionalProps:['headline','backgroundSrc','overlay'] },

  // ─── Content / Card Components ─────────────────────────────────────────────
  { name:'FeatureGrid',exportName:'FeatureGrid',category:'content',subcategory:'features',description:'3 or 4-column responsive grid of feature highlight cards',compatibleLayouts:['landing-page','saas-product','hero-features-cta'],compatibleStyles:['minimal','saas-stripe','clean-corporate'],requiredLibraries:['lucide-react'],dependencies:['FeatureCard'],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:2,intendedUsage:'Product feature showcase section',requiredProps:['features'],optionalProps:['columns','animated'] },
  { name:'FeatureCard',exportName:'FeatureCard',category:'content',subcategory:'features',description:'Individual feature card with icon, title, and description',compatibleLayouts:['landing-page','saas-product','bento-layout'],compatibleStyles:['minimal','glassmorphism','premium-dark'],requiredLibraries:['lucide-react'],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:2,intendedUsage:'Single feature highlight block',requiredProps:['title','description'],optionalProps:['icon','accent','href'] },
  { name:'PricingCard',exportName:'PricingCard',category:'content',subcategory:'pricing',description:'Subscription plan card with price, features list, and CTA',compatibleLayouts:['pricing-page','landing-page'],compatibleStyles:['saas-stripe','minimal','glassmorphism'],requiredLibraries:[],dependencies:[],previewSafe:true,animationSupport:false,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:3,intendedUsage:'Pricing/plan selector cards',requiredProps:['plan','price','features'],optionalProps:['highlighted','cta','badge'] },
  { name:'TestimonialCard',exportName:'TestimonialCard',category:'content',subcategory:'social-proof',description:'Customer testimonial with quote, avatar, and attribution',compatibleLayouts:['landing-page','saas-product'],compatibleStyles:['minimal','soft-aesthetic','clean-corporate'],requiredLibraries:[],dependencies:[],previewSafe:true,animationSupport:false,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:4,intendedUsage:'Social proof testimonial section',requiredProps:['quote','author'],optionalProps:['avatar','role','company'] },
  { name:'BlogCard',exportName:'BlogCard',category:'content',subcategory:'content',description:'Article/blog post preview card with image, title, excerpt, and meta',compatibleLayouts:['blog','news-portal','feed-social'],compatibleStyles:['minimal','editorial','magazine'],requiredLibraries:[],dependencies:[],previewSafe:true,animationSupport:false,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:3,intendedUsage:'Blog listing and content cards',requiredProps:['title','excerpt'],optionalProps:['image','author','date','tags','href'] },
  { name:'DashboardStatCard',exportName:'DashboardStatCard',category:'data',subcategory:'metrics',description:'KPI / metric stat card with value, trend, label, and icon',compatibleLayouts:['dashboard','analytics','fintech'],compatibleStyles:['minimal','premium-dark','clean-corporate'],requiredLibraries:['lucide-react'],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:1,intendedUsage:'Dashboard metric and KPI display',requiredProps:['label','value'],optionalProps:['trend','trendValue','icon','color'] },
  { name:'MetricTile',exportName:'MetricTile',category:'data',subcategory:'metrics',description:'Compact metric display tile, smaller than a stat card',compatibleLayouts:['dashboard','analytics','fintech'],compatibleStyles:['monochrome','premium-dark','futuristic'],requiredLibraries:[],dependencies:[],previewSafe:true,animationSupport:false,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:3,intendedUsage:'Dense metric displays in grids',requiredProps:['label','value'],optionalProps:['unit','change'] },
  { name:'FAQAccordion',exportName:'FAQAccordion',category:'content',subcategory:'faq',description:'Expandable FAQ list with animated open/close',compatibleLayouts:['pricing-page','landing-page','documentation'],compatibleStyles:['minimal','clean-corporate'],requiredLibraries:['lucide-react'],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:4,intendedUsage:'FAQ section for landing pages and docs',requiredProps:['items'],optionalProps:['defaultOpen','multiOpen'] },
  { name:'TimelineItem',exportName:'TimelineItem',category:'content',subcategory:'timeline',description:'Vertical timeline entry with date, title, description, and icon',compatibleLayouts:['portfolio','crm','profile-ui'],compatibleStyles:['minimal','clean-corporate'],requiredLibraries:[],dependencies:[],previewSafe:true,animationSupport:false,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:4,intendedUsage:'Activity timelines and history views',requiredProps:['date','title'],optionalProps:['description','icon','accent'] },
  { name:'ProfileCard',exportName:'ProfileCard',category:'content',subcategory:'profile',description:'User profile card with avatar, name, role, stats, and actions',compatibleLayouts:['profile-ui','feed-social','crm'],compatibleStyles:['minimal','soft-aesthetic','clean-corporate'],requiredLibraries:['lucide-react'],dependencies:[],previewSafe:true,animationSupport:false,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:3,intendedUsage:'User profile and team member display',requiredProps:['name'],optionalProps:['avatar','role','bio','stats','actions'] },
  { name:'ComparisonCard',exportName:'ComparisonCard',category:'content',subcategory:'comparison',description:'Feature comparison card or table for plan comparison',compatibleLayouts:['pricing-page'],compatibleStyles:['minimal','saas-stripe'],requiredLibraries:[],dependencies:[],previewSafe:true,animationSupport:false,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:5,intendedUsage:'Plan feature comparison tables',requiredProps:['plans','features'],optionalProps:['highlight'] },
  { name:'NotificationCard',exportName:'NotificationCard',category:'feedback',subcategory:'notifications',description:'Single notification item with icon, message, time, and read state',compatibleLayouts:['feed-social','chat-messaging','profile-ui'],compatibleStyles:['minimal','clean-corporate'],requiredLibraries:['lucide-react'],dependencies:[],previewSafe:true,animationSupport:false,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:4,intendedUsage:'Notification panel items',requiredProps:['message'],optionalProps:['icon','time','read','type'] },

  // ─── Interactive Components ────────────────────────────────────────────────
  { name:'AnimatedButton',exportName:'AnimatedButton',category:'interactive',subcategory:'input',description:'Feature-rich animated button with hover, active, and loading states',compatibleLayouts:['landing-page','saas-product','auth-ui'],compatibleStyles:['minimal','gradient-heavy','glassmorphism'],requiredLibraries:['lucide-react'],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:1,intendedUsage:'Primary CTAs and submit buttons',requiredProps:['children'],optionalProps:['variant','loading','icon','onClick'] },
  { name:'MagneticButton',exportName:'MagneticButton',category:'interactive',subcategory:'input',description:'Button that magnetically follows the cursor on hover',compatibleLayouts:['portfolio','agency-website','cursor-reactive'],compatibleStyles:['minimal','futuristic','experimental'],requiredLibraries:['framer-motion'],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:true,responsive:false,usagePriority:7,intendedUsage:'Creative CTA buttons with cursor magnetism',requiredProps:['children'],optionalProps:['strength','onClick'] },
  { name:'Tabs',exportName:'Tabs',category:'interactive',subcategory:'navigation',description:'Accessible tab navigation with animated indicator',compatibleLayouts:['settings-ui','saas-product','documentation'],compatibleStyles:['minimal','clean-corporate'],requiredLibraries:[],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:2,intendedUsage:'In-page content tab switching',requiredProps:['tabs'],optionalProps:['defaultTab','variant','onChange'] },
  { name:'Modal',exportName:'Modal',category:'interactive',subcategory:'overlay',description:'Accessible modal dialog with backdrop, close, and focus trap',compatibleLayouts:['admin-panel','ecommerce','kanban'],compatibleStyles:['minimal','glassmorphism','clean-corporate'],requiredLibraries:['lucide-react'],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:2,intendedUsage:'Confirmation dialogs, detail views, forms',requiredProps:['isOpen','onClose'],optionalProps:['title','description','children','size'] },
  { name:'Drawer',exportName:'Drawer',category:'interactive',subcategory:'overlay',description:'Slide-out drawer panel from start/end of screen',compatibleLayouts:['kanban','saas-product','ecommerce'],compatibleStyles:['minimal','clean-corporate'],requiredLibraries:['lucide-react'],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:4,intendedUsage:'Side panels, filters, detail sliders',requiredProps:['isOpen','onClose'],optionalProps:['side','title','children'] },
  { name:'SearchBar',exportName:'SearchBar',category:'interactive',subcategory:'input',description:'Accessible search input with icon, clear, and suggestions',compatibleLayouts:['documentation','search-discovery','ecommerce'],compatibleStyles:['minimal','clean-corporate'],requiredLibraries:['lucide-react'],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:2,intendedUsage:'Search input with optional autocomplete',requiredProps:[],optionalProps:['placeholder','onSearch','suggestions'] },
  { name:'CommandPalette',exportName:'CommandPalette',category:'interactive',subcategory:'navigation',description:'Cmd+K style command palette with fuzzy search',compatibleLayouts:['saas-product','IDE-style','admin-panel'],compatibleStyles:['premium-dark','minimal','monochrome'],requiredLibraries:['lucide-react'],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:false,usagePriority:5,intendedUsage:'Power-user quick navigation',requiredProps:['commands'],optionalProps:['placeholder','onCommand'] },
  { name:'ThemeSwitcher',exportName:'ThemeSwitcher',category:'interactive',subcategory:'settings',description:'Light/dark mode theme toggle with animation',compatibleLayouts:['settings-ui','saas-product'],compatibleStyles:['minimal','clean-corporate'],requiredLibraries:['lucide-react'],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:4,intendedUsage:'Theme toggle control',requiredProps:[],optionalProps:['defaultTheme','onChange'] },
  { name:'FilterBar',exportName:'FilterBar',category:'interactive',subcategory:'input',description:'Horizontal filter bar with chips, dropdowns, and active states',compatibleLayouts:['ecommerce','kanban','analytics'],compatibleStyles:['minimal','clean-corporate'],requiredLibraries:['lucide-react'],dependencies:[],previewSafe:true,animationSupport:false,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:3,intendedUsage:'Product/task filter controls',requiredProps:['filters'],optionalProps:['activeFilters','onChange','onClear'] },
  { name:'Tooltip',exportName:'Tooltip',category:'interactive',subcategory:'feedback',description:'Accessible hover tooltip with configurable position',compatibleLayouts:['admin-panel','analytics','saas-product'],compatibleStyles:['minimal','premium-dark'],requiredLibraries:[],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:4,intendedUsage:'Contextual help and label tooltips',requiredProps:['content','children'],optionalProps:['position','delay'] },
  { name:'Popover',exportName:'Popover',category:'interactive',subcategory:'overlay',description:'Floating popover panel anchored to a trigger element',compatibleLayouts:['admin-panel','saas-product','3d-product-showcase'],compatibleStyles:['minimal','clean-corporate'],requiredLibraries:[],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:5,intendedUsage:'Contextual menus and info popovers',requiredProps:['trigger','children'],optionalProps:['placement'] },

  // ─── Data / App Components ─────────────────────────────────────────────────
  { name:'DataGrid',exportName:'DataGrid',category:'data',subcategory:'table',description:'Sortable, filterable data table with pagination and row actions',compatibleLayouts:['admin-panel','crm','analytics'],compatibleStyles:['minimal','clean-corporate','monochrome'],requiredLibraries:['lucide-react'],dependencies:[],previewSafe:true,animationSupport:false,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:2,intendedUsage:'Data table with CRUD operations',requiredProps:['columns','data'],optionalProps:['sortable','filterable','pagination','onRowClick'] },
  { name:'ActivityFeed',exportName:'ActivityFeed',category:'data',subcategory:'feed',description:'Chronological activity feed with user actions and timestamps',compatibleLayouts:['dashboard','profile-ui','crm'],compatibleStyles:['minimal','clean-corporate'],requiredLibraries:['lucide-react'],dependencies:['TimelineItem'],previewSafe:true,animationSupport:false,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:3,intendedUsage:'Recent activity sidebar panels',requiredProps:['activities'],optionalProps:['maxItems','loadMore'] },
  { name:'NotificationList',exportName:'NotificationList',category:'data',subcategory:'notifications',description:'List of notifications with read/unread state and bulk actions',compatibleLayouts:['dashboard','profile-ui','chat-messaging'],compatibleStyles:['minimal','clean-corporate'],requiredLibraries:['lucide-react'],dependencies:['NotificationCard'],previewSafe:true,animationSupport:false,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:3,intendedUsage:'Notification panel and inbox',requiredProps:['notifications'],optionalProps:['onMarkRead','onClear'] },
  { name:'ChatPanel',exportName:'ChatPanel',category:'data',subcategory:'messaging',description:'Complete chat interface with message list and composer',compatibleLayouts:['chat-messaging'],compatibleStyles:['minimal','clean-corporate','premium-dark'],requiredLibraries:['lucide-react'],dependencies:['MessageBubble'],previewSafe:true,animationSupport:false,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:4,intendedUsage:'In-app chat and messaging UI',requiredProps:['messages'],optionalProps:['onSend','currentUser','placeholder'] },
  { name:'MessageBubble',exportName:'MessageBubble',category:'data',subcategory:'messaging',description:'Individual chat message bubble with avatar, time, and reactions',compatibleLayouts:['chat-messaging'],compatibleStyles:['minimal','clean-corporate'],requiredLibraries:[],dependencies:[],previewSafe:true,animationSupport:false,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:4,intendedUsage:'Chat message display',requiredProps:['message','author'],optionalProps:['time','isOwn','reactions'] },
  { name:'AnalyticsChart',exportName:'AnalyticsChart',category:'data',subcategory:'charts',description:'SVG-based chart component (line/bar/pie) using CSS animations',compatibleLayouts:['analytics','dashboard','fintech'],compatibleStyles:['minimal','premium-dark'],requiredLibraries:[],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:3,intendedUsage:'Dashboard chart visualization',requiredProps:['data','type'],optionalProps:['title','colors','height'] },
  { name:'CalendarPanel',exportName:'CalendarPanel',category:'data',subcategory:'calendar',description:'Monthly calendar grid with event indicators and date selection',compatibleLayouts:['healthtech','travel-booking','kanban'],compatibleStyles:['minimal','clean-corporate'],requiredLibraries:['lucide-react'],dependencies:[],previewSafe:true,animationSupport:false,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:4,intendedUsage:'Appointment and event calendars',requiredProps:['events'],optionalProps:['onDateSelect','defaultMonth'] },
  { name:'SettingsPanel',exportName:'SettingsPanel',category:'data',subcategory:'settings',description:'Settings section with group headers, toggles, selects, and save',compatibleLayouts:['settings-ui','saas-product'],compatibleStyles:['minimal','clean-corporate'],requiredLibraries:['lucide-react'],dependencies:[],previewSafe:true,animationSupport:false,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:3,intendedUsage:'App settings and configuration panels',requiredProps:['sections'],optionalProps:['onSave','showSaveButton'] },

  // ─── 3D / Motion Components ────────────────────────────────────────────────
  { name:'FloatingCards',exportName:'FloatingCards',category:'3d',subcategory:'motion',description:'CSS-animated floating card elements with depth and subtle motion',compatibleLayouts:['landing-page','animated-ui','3d-hero'],compatibleStyles:['glassmorphism','futuristic','premium-dark'],requiredLibraries:['framer-motion'],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:4,intendedUsage:'Visual depth elements on hero sections',requiredProps:['cards'],optionalProps:['intensity','direction'] },
  { name:'ParticleBackground',exportName:'ParticleBackground',category:'3d',subcategory:'physics',description:'Canvas-based particle field for hero backgrounds',compatibleLayouts:['particle-reactive','3d-hero','cyberpunk'],compatibleStyles:['futuristic','cyberpunk','premium-dark'],requiredLibraries:[],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:true,responsive:true,usagePriority:6,intendedUsage:'Animated particle canvas background',requiredProps:[],optionalProps:['count','color','speed','reactive'] },
  { name:'OrbitScene',exportName:'OrbitScene',category:'3d',subcategory:'3d',description:'React Three Fiber canvas with OrbitControls and basic scene setup',compatibleLayouts:['3d-hero','3d-product-showcase','webgl-ui'],compatibleStyles:['futuristic','premium-dark'],requiredLibraries:['@react-three/fiber','@react-three/drei'],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:true,physicsSupport:false,responsive:true,usagePriority:6,intendedUsage:'R3F scene wrapper with orbit controls',requiredProps:['children'],optionalProps:['background','camera','shadows'] },
  { name:'DepthLayers',exportName:'DepthLayers',category:'motion',subcategory:'parallax',description:'CSS parallax depth layers with multiple z-index planes',compatibleLayouts:['parallax-ui','scroll-storytelling','agency-website'],compatibleStyles:['editorial','gradient-heavy'],requiredLibraries:[],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:6,intendedUsage:'Parallax depth visual effects',requiredProps:['layers'],optionalProps:['intensity','perspective'] },
  { name:'MotionGrid',exportName:'MotionGrid',category:'motion',subcategory:'grid',description:'Animated grid that reveals items on scroll with stagger',compatibleLayouts:['landing-page','portfolio','animated-ui'],compatibleStyles:['minimal','gradient-heavy'],requiredLibraries:['framer-motion'],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:false,responsive:true,usagePriority:4,intendedUsage:'Stagger-animated item grids',requiredProps:['items'],optionalProps:['columns','staggerDelay'] },
  { name:'ReactiveCursorLayer',exportName:'ReactiveCursorLayer',category:'motion',subcategory:'cursor',description:'Mouse position tracking layer that moves elements with cursor',compatibleLayouts:['cursor-reactive','portfolio','agency-website'],compatibleStyles:['futuristic','experimental'],requiredLibraries:[],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:false,physicsSupport:true,responsive:false,usagePriority:8,intendedUsage:'Cursor-reactive hero elements',requiredProps:['children'],optionalProps:['intensity','ease'] },
  { name:'PhysicsCanvasWrapper',exportName:'PhysicsCanvasWrapper',category:'3d',subcategory:'physics',description:'Canvas wrapper for physics simulation UI elements',compatibleLayouts:['physics-based','particle-reactive'],compatibleStyles:['futuristic','experimental','playful'],requiredLibraries:['@react-three/fiber'],dependencies:[],previewSafe:true,animationSupport:true,threeDSupport:true,physicsSupport:true,responsive:false,usagePriority:8,intendedUsage:'Physics-based interactive elements',requiredProps:['children'],optionalProps:['gravity','bounds'] },
];

export function findCompatibleComponents(layoutId: string, styleId?: string): ComponentEntry[] {
  return COMPONENT_REGISTRY.filter(c => {
    const layoutMatch = c.compatibleLayouts.includes(layoutId) || c.usagePriority <= 3;
    const styleMatch = !styleId || c.compatibleStyles.includes(styleId) || c.compatibleStyles.length === 0;
    return layoutMatch && styleMatch;
  }).sort((a, b) => a.usagePriority - b.usagePriority);
}

export function getComponentByName(name: string): ComponentEntry | undefined {
  return COMPONENT_REGISTRY.find(c => c.name === name || c.exportName === name);
}

export function getPreviewSafeComponents(): ComponentEntry[] {
  return COMPONENT_REGISTRY.filter(c => c.previewSafe);
}

export function get3DComponents(): ComponentEntry[] {
  return COMPONENT_REGISTRY.filter(c => c.threeDSupport);
}

export function getAllComponentNames(): string[] {
  return COMPONENT_REGISTRY.map(c => c.name);
}
