export type LayoutCategory = 'website'|'saas'|'dashboard'|'auth'|'content'|'ecommerce'|'social'|'app'|'enterprise'|'edtech'|'fintech'|'healthtech'|'visual-style'|'motion'|'depth'|'physics'|'structure'|'device';
export type AnimationLevel = 'none'|'subtle'|'moderate'|'high'|'cinematic';
export type ComplexityLevel = 'simple'|'moderate'|'complex'|'advanced';

export interface LayoutEntry {
  id: string; name: string; category: LayoutCategory; description: string;
  keywords: string[]; structure: string[]; compatibleStyles: string[];
  compatibleComponents: string[]; complexity: ComplexityLevel; responsive: boolean;
  animationSuitability: AnimationLevel; depthUISuitability: boolean;
  physicsSuitability: boolean; previewSafe: boolean; bestFitScenarios: string[];
}

export const LAYOUT_REGISTRY: LayoutEntry[] = [
  { id:'landing-page',name:'Landing Page UI',category:'website',description:'Marketing-oriented single page with hero, features, CTA, and social proof',keywords:['landing page','marketing page','homepage','product page','landing'],structure:['Hero','Features','Social Proof','Pricing','CTA','Footer'],compatibleStyles:['minimal','saas-stripe','glassmorphism','gradient-heavy','bold-typography'],compatibleComponents:['HeroSection','FeatureGrid','PricingCard','TestimonialCard','CTASection'],complexity:'moderate',responsive:true,animationSuitability:'moderate',depthUISuitability:true,physicsSuitability:false,previewSafe:true,bestFitScenarios:['SaaS product launch','startup homepage','product showcase'] },
  { id:'saas-product',name:'SaaS Product UI',category:'saas',description:'Product-focused UI for SaaS applications with appbar, sidebar, and workspace',keywords:['saas','software product','tool ui','productivity app','saas ui'],structure:['Topbar','Sidebar','Main Workspace','Right Panel','Footer'],compatibleStyles:['minimal','saas-stripe','clean-corporate'],compatibleComponents:['Sidebar','Header','DataGrid','CommandPalette','SettingsPanel'],complexity:'complex',responsive:true,animationSuitability:'subtle',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Project management tools','developer tools','analytics platforms'] },
  { id:'dashboard',name:'Dashboard UI',category:'dashboard',description:'Data-heavy admin dashboard with metrics, charts, tables, and navigation',keywords:['dashboard','admin dashboard','analytics dashboard','control panel','overview','metrics dashboard'],structure:['Sidebar Nav','Top Header','Metric Cards','Charts Area','Data Table','Activity Feed'],compatibleStyles:['minimal','clean-corporate','premium-dark','monochrome'],compatibleComponents:['Sidebar','DashboardStatCard','AnalyticsChart','DataGrid','ActivityFeed'],complexity:'complex',responsive:true,animationSuitability:'subtle',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Business intelligence','ops monitoring','admin panels'] },
  { id:'admin-panel',name:'Admin Panel UI',category:'dashboard',description:'Full-featured admin control interface with CRUD tables and user management',keywords:['admin panel','admin ui','back office','cms admin','management panel'],structure:['Sidebar','Header','Data Tables','Forms','Modal Dialogs','Breadcrumbs'],compatibleStyles:['clean-corporate','minimal','monochrome'],compatibleComponents:['Sidebar','Table','Modal','SearchBar','FilterBar'],complexity:'complex',responsive:true,animationSuitability:'none',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['User management','content management','system settings'] },
  { id:'portfolio',name:'Portfolio UI',category:'website',description:'Creative personal or agency portfolio showcasing work and skills',keywords:['portfolio','personal website','creative portfolio','designer portfolio','developer portfolio'],structure:['Hero','About','Work Grid','Case Studies','Contact'],compatibleStyles:['minimal','editorial','bold-typography','elegant','luxury'],compatibleComponents:['HeroSection','FeatureGrid','TimelineItem'],complexity:'moderate',responsive:true,animationSuitability:'moderate',depthUISuitability:true,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Freelancer showcase','agency website','developer portfolio'] },
  { id:'ecommerce',name:'E-Commerce UI',category:'ecommerce',description:'Online store with product listings, cart, checkout, and product detail',keywords:['ecommerce','e-commerce','online store','shop','shopping','store'],structure:['Header + Cart','Category Filters','Product Grid','Product Detail','Cart','Checkout'],compatibleStyles:['minimal','clean-corporate','luxury','soft-aesthetic'],compatibleComponents:['SearchBar','FilterBar','FeatureCard','Modal'],complexity:'complex',responsive:true,animationSuitability:'subtle',depthUISuitability:true,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Fashion stores','electronics shops','marketplace listings'] },
  { id:'blog',name:'Blog UI',category:'content',description:'Content-first blog with article listing, reading view, and categories',keywords:['blog','content site','articles','reading site','news blog'],structure:['Header','Featured Post','Article Grid','Categories','Sidebar','Footer'],compatibleStyles:['editorial','minimal','bold-typography','magazine'],compatibleComponents:['BlogCard','SearchBar'],complexity:'simple',responsive:true,animationSuitability:'subtle',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Personal blogs','tech blogs','editorial publications'] },
  { id:'documentation',name:'Documentation UI',category:'content',description:'Technical documentation with sidebar navigation, search, and code examples',keywords:['documentation','docs','api docs','developer docs','guides','readme'],structure:['Top Header','Left Sidebar (Nav)','Main Content','Right TOC Sidebar','Code Blocks'],compatibleStyles:['minimal','monochrome','clean-corporate'],compatibleComponents:['Sidebar','SearchBar','FAQAccordion'],complexity:'moderate',responsive:true,animationSuitability:'none',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['SDKs','developer portals','technical guides'] },
  { id:'pricing-page',name:'Pricing Page UI',category:'website',description:'Pricing comparison page with plan cards, feature matrix, and FAQ',keywords:['pricing','pricing page','plans','subscription plans','pricing cards'],structure:['Header','Plan Toggle','Pricing Cards','Feature Comparison Table','FAQ'],compatibleStyles:['saas-stripe','minimal','gradient-heavy'],compatibleComponents:['PricingCard','ComparisonCard','FAQAccordion','AnimatedButton'],complexity:'moderate',responsive:true,animationSuitability:'subtle',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['SaaS pricing','subscription services','freemium models'] },
  { id:'auth-ui',name:'Auth UI',category:'auth',description:'Authentication screens: login, signup, password reset with validation',keywords:['login','signup','sign in','register','authentication','auth','password reset'],structure:['Centered Card','Form Fields','Submit Button','Social Auth','Links'],compatibleStyles:['minimal','glassmorphism','premium-dark','clean-corporate'],compatibleComponents:['Modal','AnimatedButton','Tooltip'],complexity:'simple',responsive:true,animationSuitability:'subtle',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Web app auth','SaaS onboarding','user management'] },
  { id:'settings-ui',name:'Settings UI',category:'app',description:'Application settings with sections, toggles, and preference management',keywords:['settings','preferences','configuration','options panel','account settings'],structure:['Sidebar Sections','Setting Groups','Toggles','Save Button'],compatibleStyles:['minimal','clean-corporate','monochrome'],compatibleComponents:['Sidebar','SettingsPanel','Tabs','ThemeSwitcher'],complexity:'moderate',responsive:true,animationSuitability:'none',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['User preferences','system configuration','notification settings'] },
  { id:'chat-messaging',name:'Chat / Messaging UI',category:'social',description:'Real-time chat interface with message threads, online presence, and media',keywords:['chat','messaging','direct message','conversations','inbox','chat ui'],structure:['Contacts Sidebar','Chat Header','Message Feed','Composer','Media Panel'],compatibleStyles:['minimal','clean-corporate','premium-dark'],compatibleComponents:['ChatPanel','MessageBubble','SearchBar','NotificationList'],complexity:'complex',responsive:true,animationSuitability:'subtle',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Slack-like tools','DM systems','support chat'] },
  { id:'feed-social',name:'Feed / Social UI',category:'social',description:'Social media feed with posts, interactions, stories, and user discovery',keywords:['feed','social feed','timeline','social media','posts','newsfeed'],structure:['Stories/Highlights','Post Feed','Post Card','Interaction Bar','Right Panel'],compatibleStyles:['minimal','soft-aesthetic','clean-corporate','premium-dark'],compatibleComponents:['ActivityFeed','ProfileCard','NotificationCard'],complexity:'moderate',responsive:true,animationSuitability:'moderate',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Twitter-like apps','Instagram feed','LinkedIn feed'] },
  { id:'kanban',name:'Kanban / Project Management UI',category:'app',description:'Kanban board with columns, cards, drag-and-drop, and project tracking',keywords:['kanban','project management','task board','trello','jira','board'],structure:['Top Header','Board Columns','Task Cards','Card Detail Modal','Add Card CTA'],compatibleStyles:['clean-corporate','minimal','premium-dark'],compatibleComponents:['PanelGroup','Modal','Drawer','FilterBar'],complexity:'complex',responsive:true,animationSuitability:'moderate',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Project tracking','sprint boards','team workflows'] },
  { id:'analytics',name:'Analytics UI',category:'dashboard',description:'Data analytics interface with KPIs, charts, filters, and drill-downs',keywords:['analytics','metrics','reports','data visualization','business intelligence','kpi'],structure:['Top Filters','KPI Cards','Charts Row','Data Table','Segment Panels'],compatibleStyles:['premium-dark','minimal','monochrome','clean-corporate'],compatibleComponents:['DashboardStatCard','AnalyticsChart','FilterBar','DataGrid'],complexity:'complex',responsive:true,animationSuitability:'subtle',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Marketing analytics','product metrics','financial reporting'] },
  { id:'fintech',name:'Fintech UI',category:'fintech',description:'Financial product UI with portfolio, transactions, charts, and trading',keywords:['fintech','finance','trading','crypto','banking','wallet','portfolio dashboard','financial'],structure:['Portfolio Overview','Asset List','Transaction Feed','Charts','Trade Panel'],compatibleStyles:['premium-dark','futuristic','cyberpunk','glassmorphism','monochrome'],compatibleComponents:['DashboardStatCard','AnalyticsChart','DataGrid','MetricTile'],complexity:'complex',responsive:true,animationSuitability:'moderate',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Crypto dashboards','banking apps','trading platforms'] },
  { id:'edtech',name:'EdTech UI',category:'edtech',description:'Learning platform with courses, progress tracking, quizzes, and content',keywords:['edtech','learning platform','course ui','education','elearning','online course'],structure:['Course Catalog','Lesson Viewer','Progress Tracker','Quiz Interface','Certificate'],compatibleStyles:['soft-aesthetic','playful','clean-corporate','minimal'],compatibleComponents:['FeatureCard','VersionTimeline','Tabs'],complexity:'complex',responsive:true,animationSuitability:'moderate',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Online courses','quiz platforms','coding bootcamps'] },
  { id:'crm',name:'CRM UI',category:'enterprise',description:'Customer relationship management with contact list, pipeline, and activities',keywords:['crm','customer relationship','sales pipeline','contacts','lead management'],structure:['Contact List','Pipeline Board','Contact Detail','Activity Timeline','Reports'],compatibleStyles:['clean-corporate','minimal','monochrome'],compatibleComponents:['DataGrid','ProfileCard','ActivityFeed','AnalyticsChart'],complexity:'complex',responsive:true,animationSuitability:'subtle',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Sales teams','customer support','lead management'] },
  { id:'minimal-style',name:'Minimal UI Style',category:'visual-style',description:'Clean, white-space-forward design with restrained typography and subtle depth',keywords:['minimal','clean','simple','whitespace','minimalist','clean design'],structure:['Sparse Layout','Strong Typography','Single Focal Point'],compatibleStyles:['minimal'],compatibleComponents:['HeroSection','FeatureCard','AnimatedButton'],complexity:'simple',responsive:true,animationSuitability:'subtle',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Apple-inspired products','luxury brands','focused SaaS tools'] },
  { id:'glassmorphism',name:'Glassmorphism UI',category:'visual-style',description:'Frosted glass panels with translucency, blur, and layered depth',keywords:['glassmorphism','frosted glass','glass effect','blur glass','transparent glass','backdrop blur'],structure:['Full Background','Glass Cards','Blurred Panels'],compatibleStyles:['glassmorphism','futuristic','premium-dark'],compatibleComponents:['HeroSection','Modal','FeatureCard'],complexity:'moderate',responsive:true,animationSuitability:'moderate',depthUISuitability:true,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Fintech apps','crypto dashboards','premium modals'] },
  { id:'neumorphism',name:'Neumorphism UI',category:'visual-style',description:'Soft extruded shapes with dual inner/outer shadows on neutral backgrounds',keywords:['neumorphism','neomorphism','soft ui','extruded','soft shadow'],structure:['Monochrome Background','Soft-Shadow Cards','Pressed Buttons'],compatibleStyles:['neumorphism','soft-aesthetic'],compatibleComponents:['FeatureCard','AnimatedButton','Tabs'],complexity:'moderate',responsive:true,animationSuitability:'subtle',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Smart home UIs','health apps','music controls'] },
  { id:'cyberpunk',name:'Cyberpunk UI',category:'visual-style',description:'High-contrast neon-on-dark aesthetic with glitch effects and tech grid',keywords:['cyberpunk','neon','glitch','dark neon','hacker','tech noir','cyber'],structure:['Dark Background','Neon Border Cards','Glitch Typography','HUD Elements'],compatibleStyles:['cyberpunk','neon','sci-fi-hud'],compatibleComponents:['HeroSection','DashboardStatCard','MetricTile'],complexity:'complex',responsive:true,animationSuitability:'high',depthUISuitability:true,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Gaming UIs','crypto platforms','hacker-aesthetic tools'] },
  { id:'futuristic',name:'Futuristic UI',category:'visual-style',description:'Forward-looking sci-fi aesthetic with sleek forms, gradients, and tech feel',keywords:['futuristic','sci-fi','future','space','tech ui','futurism'],structure:['Dark Background','Gradient Accents','Geometric Layouts','Glowing CTAs'],compatibleStyles:['futuristic','sci-fi-hud','gradient-heavy','glassmorphism'],compatibleComponents:['HeroSection','AnimatedHero','MetricTile','FloatingCards'],complexity:'complex',responsive:true,animationSuitability:'high',depthUISuitability:true,physicsSuitability:false,previewSafe:true,bestFitScenarios:['AI products','space-tech startups','drone/robotics UIs'] },
  { id:'bento-grid',name:'Bento Grid UI',category:'visual-style',description:'Magazine-style asymmetric grid layout popularized by Apple product pages',keywords:['bento','bento grid','feature grid','asymmetric grid','apple-style grid'],structure:['Responsive Grid','Variable-Size Cards','Feature Highlights','Icon + Text Blocks'],compatibleStyles:['bento-grid','minimal','saas-stripe'],compatibleComponents:['BentoShell','FeatureCard','DashboardStatCard'],complexity:'moderate',responsive:true,animationSuitability:'moderate',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Feature pages','product showcases','app landing pages'] },
  { id:'premium-dark',name:'Premium Dark UI',category:'visual-style',description:'Rich, sophisticated dark mode with high-quality typography and subtle depth',keywords:['dark mode','premium dark','dark ui','dark theme','black ui','dark'],structure:['Dark Background','Elevated Surface Cards','Accent Highlights','Strong CTAs'],compatibleStyles:['premium-dark','glassmorphism','gradient-heavy'],compatibleComponents:['HeroSection','FeatureCard','PricingCard','DashboardStatCard'],complexity:'moderate',responsive:true,animationSuitability:'moderate',depthUISuitability:true,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Developer tools','design apps','fintech platforms'] },
  { id:'luxury',name:'Luxury UI',category:'visual-style',description:'Ultra-premium editorial aesthetic with gold accents, serif fonts, and whitespace',keywords:['luxury','premium','high-end','exclusive','luxury brand','elegant'],structure:['Expansive Whitespace','High-Res Imagery','Serif Typography','Minimal CTAs'],compatibleStyles:['luxury','elegant','editorial'],compatibleComponents:['HeroSection','FeatureCard','TeamCard'],complexity:'moderate',responsive:true,animationSuitability:'moderate',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Jewelry brands','fashion houses','premium real estate'] },
  { id:'animated-ui',name:'Animated UI',category:'motion',description:'Motion-enhanced interface with smooth transitions and enter animations',keywords:['animated','animation','framer motion','transition','animated ui','motion'],structure:['Entry Animations','Hover States','Page Transitions','Loading Animations'],compatibleStyles:['minimal','gradient-heavy','premium-dark'],compatibleComponents:['AnimatedHero','AnimatedButton','FloatingCards','MotionGrid'],complexity:'moderate',responsive:true,animationSuitability:'high',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Product launches','portfolio reveals','onboarding flows'] },
  { id:'scroll-storytelling',name:'Scroll-Driven Storytelling UI',category:'motion',description:'Narrative experience where content reveals progressively as user scrolls',keywords:['scroll animation','scroll story','parallax scroll','storytelling scroll'],structure:['Fixed Scroll Container','Chapter Sections','Progress Indicator','Reveal Triggers'],compatibleStyles:['editorial','gradient-heavy','bold-typography'],compatibleComponents:['HeroSection','MotionGrid','DepthLayers'],complexity:'advanced',responsive:true,animationSuitability:'cinematic',depthUISuitability:true,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Brand stories','product feature showcases','interactive reports'] },
  { id:'depth-hero',name:'Depth Hero UI',category:'depth',description:'Landing page hero with heavy parallax layers and floating transparent cards',keywords:['depth hero','parallax hero','framer hero','floating background'],structure:['Absolute Background Glows','Parallax Floating Shapes','HTML Overlay Header','CTA Layer'],compatibleStyles:['futuristic','premium-dark','glassmorphism'],compatibleComponents:['FloatingCards','HeroSection'],complexity:'advanced',responsive:true,animationSuitability:'cinematic',depthUISuitability:true,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Product reveals','creative agency homepages','SaaS premium landing'] },
  { id:'feature-depth-reveal',name:'Feature Depth Reveal UI',category:'depth',description:'Scroll-linked layered section that reveals feature cards against moving backgrounds',keywords:['depth reveal','feature reveal','scroll depth','layered features'],structure:['Scroll Container','Sticky Sidebar','Floating Info Cards','Background Motion'],compatibleStyles:['minimal','premium-dark','luxury'],compatibleComponents:['MotionGrid','Popover'],complexity:'advanced',responsive:true,animationSuitability:'moderate',depthUISuitability:true,physicsSuitability:false,previewSafe:true,bestFitScenarios:['E-commerce product pages','feature deep dives'] },
  { id:'premium-depth-page',name:'Premium Depth Page',category:'depth',description:'A massive multi-section page relying fully on z-index depth, blur layers, and scroll-linked framer variables',keywords:['premium depth','framer multi page','immersive depth'],structure:['Full Scroll Wrapper','Hero Depth Layer','Blur Separators','Interactive Deep Footer'],compatibleStyles:['futuristic','cyberpunk','premium-dark'],compatibleComponents:['DepthLayers','ParticleBackground'],complexity:'advanced',responsive:true,animationSuitability:'cinematic',depthUISuitability:true,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Creative experiments','interactive artworks','immersive landing pages'] },
  { id:'physics-based',name:'Physics-Based UI',category:'physics',description:'Spring, inertia, and mass-based interaction models with framer-motion or r3f',keywords:['physics','spring','inertia','physics-based','elastic','bouncy'],structure:['Physics Canvas','Draggable Items','Spring Controllers','Simulation Space'],compatibleStyles:['experimental','playful','futuristic'],compatibleComponents:['PhysicsCanvasWrapper','FloatingCards','MagneticButton'],complexity:'advanced',responsive:false,animationSuitability:'high',depthUISuitability:false,physicsSuitability:true,previewSafe:true,bestFitScenarios:['Interactive games','creative experiments','playful dashboards'] },
  { id:'particle-reactive',name:'Particle-Reactive UI',category:'physics',description:'Particle systems that react to mouse movement or data input',keywords:['particle','particles','particle system','reactive particles','particle background'],structure:['Full-Screen Canvas','Particle Layer','UI Overlay'],compatibleStyles:['futuristic','cyberpunk','premium-dark'],compatibleComponents:['ParticleBackground','ReactiveCursorLayer'],complexity:'advanced',responsive:true,animationSuitability:'cinematic',depthUISuitability:true,physicsSuitability:true,previewSafe:true,bestFitScenarios:['Hero backgrounds','data visualization','brand intros'] },
  { id:'hero-features-cta',name:'Hero + Features + CTA Layout',category:'structure',description:'Classic SaaS landing structure: hero → features → social proof → CTA',keywords:['hero features cta','landing structure','saas layout','hero section cta'],structure:['Hero Section','Features Row','Testimonials','Pricing','CTA','Footer'],compatibleStyles:['saas-stripe','minimal','gradient-heavy'],compatibleComponents:['HeroSection','FeatureGrid','TestimonialCard','CTASection'],complexity:'moderate',responsive:true,animationSuitability:'subtle',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['SaaS homepages','product launches','marketing pages'] },
  { id:'sidebar-header-content',name:'Sidebar + Header + Content Layout',category:'structure',description:'Classic app shell with persistent sidebar, sticky header, and scrollable content',keywords:['sidebar layout','app shell','sidebar navigation layout','app layout'],structure:['Sidebar','Topbar','Main Content','Optional Right Panel'],compatibleStyles:['clean-corporate','minimal','premium-dark'],compatibleComponents:['Sidebar','Header','PanelGroup','SplitPanel'],complexity:'moderate',responsive:true,animationSuitability:'subtle',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Admin panels','SaaS workspaces','dashboards'] },
  { id:'split-screen',name:'Split-Screen Layout',category:'structure',description:'Two-panel layout dividing screen between two equal or weighted areas',keywords:['split screen','two panel','side by side','dual panel','split view'],structure:['Left Panel','Right Panel','Optional Divider','Resize Handle'],compatibleStyles:['minimal','clean-corporate','premium-dark'],compatibleComponents:['SplitPanel','PanelGroup'],complexity:'simple',responsive:true,animationSuitability:'subtle',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Code editors','comparison views','email clients'] },
  { id:'bento-layout',name:'Bento Grid Layout',category:'structure',description:'Pinterest-style asymmetric card grid for feature-rich pages',keywords:['bento grid layout','bento box','feature bento','asymmetric cards'],structure:['Multi-Column Bento Grid','Variable-Size Cards','Highlight Tile'],compatibleStyles:['minimal','saas-stripe','bento-grid'],compatibleComponents:['BentoShell','FeatureCard','DashboardStatCard'],complexity:'moderate',responsive:true,animationSuitability:'moderate',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Feature showcases','product pages','app landing pages'] },
  { id:'full-screen-snap',name:'Full-Screen Section Snap Layout',category:'structure',description:'Scroll snapping full-viewport sections with one section per page',keywords:['scroll snap','full screen sections','fullpage','page snap','section snap'],structure:['Full-Screen Sections','Navigation Dots','Progress Indicator'],compatibleStyles:['editorial','gradient-heavy'],compatibleComponents:['SectionWrapper','HeroSection','MotionGrid'],complexity:'moderate',responsive:true,animationSuitability:'high',depthUISuitability:true,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Presentations','portfolio sites','product showcases'] },
  { id:'wizard-flow',name:'Wizard / Flow Layout',category:'structure',description:'Multi-step form/flow with progress indicator and step-by-step navigation',keywords:['wizard','multi-step','onboarding','stepper','flow','step by step'],structure:['Progress Bar','Step Content','Back/Next Controls','Summary Step'],compatibleStyles:['clean-corporate','minimal','soft-aesthetic'],compatibleComponents:['Tabs','AnimatedButton','Modal'],complexity:'moderate',responsive:true,animationSuitability:'moderate',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Onboarding flows','checkout','form wizards'] },
  { id:'IDE-style',name:'IDE-Style Layout',category:'structure',description:'Code editor-inspired multi-panel layout with sidebar, editor, and terminal',keywords:['ide','code editor','editor layout','vscode layout','developer ide'],structure:['Activity Bar','File Tree','Editor Tabs','Editor Body','Terminal Panel'],compatibleStyles:['monochrome','premium-dark','minimal'],compatibleComponents:['Sidebar','PanelGroup','Tabs','SplitPanel'],complexity:'advanced',responsive:false,animationSuitability:'none',depthUISuitability:false,physicsSuitability:false,previewSafe:true,bestFitScenarios:['Dev tools','online IDEs','code playgrounds'] },
];

export function findMatchingLayouts(prompt: string, maxResults = 3): LayoutEntry[] {
  const normalized = prompt.toLowerCase();
  const scored = LAYOUT_REGISTRY.map(entry => {
    let score = 0;
    for (const kw of entry.keywords) {
      if (normalized.includes(kw)) score += kw.split(' ').length;
    }
    return { entry, score };
  });
  return scored.filter(s => s.score > 0).sort((a, b) => b.score - a.score).slice(0, maxResults).map(s => s.entry);
}

export function getLayoutById(id: string): LayoutEntry | undefined {
  return LAYOUT_REGISTRY.find(e => e.id === id);
}

export function getDepthUICompatibleLayouts(): LayoutEntry[] {
  return LAYOUT_REGISTRY.filter(e => e.depthUISuitability && e.previewSafe);
}

export function getLayoutsByCategory(category: LayoutCategory): LayoutEntry[] {
  return LAYOUT_REGISTRY.filter(e => e.category === category);
}
