import type { UIIntent } from './validation/schemas';

interface GeneratedTests {
  rtl: string;
  playwright: string;
}

export function generateTests(intent: UIIntent, componentCode: string): GeneratedTests {
  const { componentName, fields, interactions, componentType } = intent;

  const rtl = generateRTLTests(componentName, fields, interactions);
  const playwright = generatePlaywrightTests(componentName, fields, interactions, componentType);

  return { rtl, playwright };
}

function generateRTLTests(
  componentName: string,
  fields: UIIntent['fields'],
  interactions: UIIntent['interactions'],
): string {
  const inputFields = fields.filter(f => ['text', 'email', 'password', 'textarea', 'number', 'tel'].includes(f.type));
  const buttonFields = fields.filter(f => f.type === 'button');
  const selectFields = fields.filter(f => f.type === 'select');
  const requiredFields = fields.filter(f => f.required);

  const interactionTests = interactions.map((interaction, i) => {
    if (interaction.trigger === 'submit') {
      return `
  it('handles form submission', async () => {
    const user = userEvent.setup();
    render(<${componentName} />);
    ${inputFields.slice(0, 2).map(f =>
      `await user.type(screen.getByLabelText('${f.label}'), 'test-value');`
    ).join('\n    ')}
    const submitButton = screen.getByRole('button', { name: /submit/i });
    await user.click(submitButton);
    // Verify feedback state
    expect(submitButton).not.toBeDisabled();
  });`;
    }
    if (interaction.trigger === 'click') {
      return `
  it('handles click interaction ${i + 1}', async () => {
    const user = userEvent.setup();
    render(<${componentName} />);
    // Test click interaction: ${interaction.action}
  });`;
    }
    return '';
  }).filter(Boolean);

  const validationTests = requiredFields.length > 0 ? `
  it('shows validation errors for required fields when empty', async () => {
    const user = userEvent.setup();
    render(<${componentName} />);
    const submitButton = screen.getByRole('button', { name: /submit/i });
    await user.click(submitButton);
    ${requiredFields.slice(0, 2).map(f =>
      `expect(screen.queryByText(/required/i) || screen.queryByRole('alert')).toBeInTheDocument();`
    ).join('\n    ')}
  });` : '';

  const inputInteractionTests = inputFields.slice(0, 3).map(f => `
  it('allows typing in ${f.label} field', async () => {
    const user = userEvent.setup();
    render(<${componentName} />);
    const input = screen.getByLabelText('${f.label}');
    await user.type(input, 'test input value');
    expect(input).toHaveValue('test input value');
  });`).join('');

  const selectInteractionTests = selectFields.slice(0, 2).map(f => `
  it('allows selecting option in ${f.label}', async () => {
    const user = userEvent.setup();
    render(<${componentName} />);
    const select = screen.getByLabelText('${f.label}');
    ${f.options.length > 0 ? `await user.selectOptions(select, '${f.options[0]}');
    expect(select).toHaveValue('${f.options[0]}');` : '// No options defined'}
  });`).join('');

  const buttonTests = buttonFields.slice(0, 2).map(f => `
  it('renders ${f.label} button', () => {
    render(<${componentName} />);
    expect(screen.getByRole('button', { name: /${f.label}/i })).toBeInTheDocument();
  });`).join('');

  return `/**
 * Auto-generated React Testing Library tests
 * Component: ${componentName}
 * Generated by AI-Powered Accessibility-First UI Engine
 */

import React from 'react';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import '@testing-library/jest-dom';
import ${componentName} from '../components/${componentName}';

describe('${componentName}', () => {
  // ─── Render Tests ──────────────────────────────────────────────────────────

  it('renders without crashing', () => {
    render(<${componentName} />);
    expect(document.body).toBeInTheDocument();
  });

${fields.slice(0, 4).map(f => `  it('renders ${f.label}', () => {
    render(<${componentName} />);
    expect(screen.getByText('${f.label}')).toBeInTheDocument();
  });`).join('\n\n')}

  // ─── Interaction Tests ─────────────────────────────────────────────────────
${inputInteractionTests}
${selectInteractionTests}
${buttonTests}
${interactionTests.join('')}
${validationTests}

  // ─── Accessibility Tests ───────────────────────────────────────────────────

  it('has no heading structure violations', () => {
    render(<${componentName} />);
    // All headings should be findable by role
    const headings = screen.queryAllByRole('heading');
    headings.forEach(heading => {
      expect(heading).toBeVisible();
    });
  });

  it('all interactive elements are keyboard accessible', () => {
    render(<${componentName} />);
    const buttons = screen.queryAllByRole('button');
    buttons.forEach(button => {
      expect(button).not.toHaveAttribute('tabindex', '-1');
    });
  });

  it('form inputs have associated labels', () => {
    render(<${componentName} />);
    const inputs = document.querySelectorAll('input, textarea, select');
    inputs.forEach(input => {
      const id = input.getAttribute('id');
      if (id) {
        const label = document.querySelector(\`label[for="\${id}"]\`);
        const ariaLabel = input.getAttribute('aria-label');
        expect(label || ariaLabel).toBeTruthy();
      }
    });
  });

  it('buttons have accessible names', () => {
    render(<${componentName} />);
    const buttons = screen.queryAllByRole('button');
    buttons.forEach(button => {
      expect(button).toHaveAccessibleName();
    });
  });
});
`;
}

function generatePlaywrightTests(
  componentName: string,
  fields: UIIntent['fields'],
  _interactions: UIIntent['interactions'],
  componentType: string,
): string {
  const inputFields = fields.filter(f => ['text', 'email', 'password', 'textarea'].includes(f.type));
  const requiredFields = fields.filter(f => f.required);

  const fillFormSteps = inputFields.slice(0, 3).map(f => {
    if (f.type === 'password') return `  await page.fill('input#${f.id}', 'SecurePass123!');`;
    if (f.type === 'email') return `  await page.fill('input#${f.id}', 'test@example.com');`;
    return `  await page.fill('input#${f.id}, textarea#${f.id}', 'Test Value');`;
  }).join('\n');

  return `/**
 * Auto-generated Playwright E2E tests
 * Component: ${componentName} (${componentType})
 * Generated by AI-Powered Accessibility-First UI Engine
 * 
 * Prerequisites: Run 'npx playwright install' before running these tests.
 * Update BASE_URL to point to your running application.
 */

import { test, expect } from '@playwright/test';

const BASE_URL = process.env.BASE_URL || 'http://localhost:3000';

test.describe('${componentName} E2E Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(BASE_URL);
  });

  // ─── Visual Tests ──────────────────────────────────────────────────────────

  test('page loads and component is visible', async ({ page }) => {
    await expect(page).toHaveTitle(/.+/);
    await expect(page.locator('body')).toBeVisible();
  });

  // ─── Keyboard Navigation Tests ─────────────────────────────────────────────

  test('all interactive elements are reachable by Tab', async ({ page }) => {
    await page.keyboard.press('Tab');
    const focusedElement = await page.evaluate(() => document.activeElement?.tagName);
    expect(['INPUT', 'BUTTON', 'SELECT', 'TEXTAREA', 'A']).toContain(focusedElement);
  });

  test('form can be submitted via keyboard', async ({ page }) => {
${fillFormSteps}
    await page.keyboard.press('Tab'); // Move to submit
    await page.keyboard.press('Enter');
    // Verify some feedback
    await expect(page.locator('body')).toBeVisible();
  });

  // ─── Accessibility Tests ───────────────────────────────────────────────────

  test('no accessibility violations (axe-core)', async ({ page }) => {
    // Install: npm install --save-dev @axe-core/playwright
    // import { checkA11y } from '@axe-core/playwright';
    // await checkA11y(page);
    // Placeholder: manual ARIA check
    const buttons = await page.locator('button').all();
    for (const button of buttons) {
      const name = await button.getAttribute('aria-label') || await button.textContent();
      expect(name?.trim()).toBeTruthy();
    }
  });

  test('focus indicators are visible', async ({ page }) => {
    await page.keyboard.press('Tab');
    const focusedEl = page.locator(':focus');
    await expect(focusedEl).toBeVisible();
  });

${requiredFields.length > 0 ? `  // ─── Validation Tests ──────────────────────────────────────────────────────

  test('shows errors when required fields are empty', async ({ page }) => {
    const submitButton = page.locator('button[type="submit"]').first();
    if (await submitButton.count() > 0) {
      await submitButton.click();
      // Verify error messages appear
      const errors = page.locator('[role="alert"], .text-red-500, [aria-live="polite"]');
      // Errors may or may not appear depending on implementation
      await expect(page.locator('body')).toBeVisible();
    }
  });` : ''}

  // ─── Mobile Viewport Tests ─────────────────────────────────────────────────

  test('component is responsive on mobile', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 });
    await expect(page.locator('body')).toBeVisible();
    // Ensure no horizontal scroll
    const scrollWidth = await page.evaluate(() => document.documentElement.scrollWidth);
    const clientWidth = await page.evaluate(() => document.documentElement.clientWidth);
    expect(scrollWidth).toBeLessThanOrEqual(clientWidth + 5); // 5px tolerance
  });
});
`;
}
