/**
 * @file base.ts
 * Defines the universal AIAdapter interface.
 * Every provider (OpenAI, Ollama, Anthropic, DeepSeek) implements this
 * contract, making the rest of the application provider-agnostic.
 */

import type { Tool, ToolCall, ToolChoice } from '../tools';

// ─── Message Types ────────────────────────────────────────────────────────────

export type MessageRole = 'system' | 'user' | 'assistant';

export interface Message {
  role: MessageRole;
  content: string;
}

// ─── Request / Response ───────────────────────────────────────────────────────

export interface GenerateOptions {
  /** Provider-specific model identifier, e.g. "gpt-4o" or "deepseek-coder:6.7b" */
  model: string;
  messages: Message[];
  temperature?: number;
  maxTokens?: number;
  /** Response format hint (only honoured by providers that support it) */
  responseFormat?: 'json_object' | 'text';
  /** Tools / functions the model may call */
  tools?: Tool[];
  /** Controls which tool (if any) the model must call */
  toolChoice?: ToolChoice;
}

export interface GenerateResult {
  /** The text generated by the model */
  content: string;
  /** Tool calls the model requested (populated when the model uses tools) */
  toolCalls?: ToolCall[];
  /** Token usage, if the provider returns it */
  usage?: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
    /** True if this result was served from the local cache */
    cached?: boolean;
  };
  /** Raw provider response, useful for debugging */
  raw?: unknown;
}

// ─── Streaming ────────────────────────────────────────────────────────────────

export interface StreamChunk {
  /** Incremental text delta */
  delta: string;
  /** Set to true on the final chunk */
  done: boolean;
  /** Full usage summary, available on the final chunk for providers that support it */
  usage?: GenerateResult['usage'];
}

// ─── Adapter Interface ────────────────────────────────────────────────────────

export interface AIAdapter {
  /** The canonical name of the provider: "openai" | "ollama" | "anthropic" | "deepseek" */
  readonly provider: string;

  /**
   * Single-shot, non-streaming generation.
   * Resolves with the complete response once the model finishes.
   */
  generate(options: GenerateOptions): Promise<GenerateResult>;

  /**
   * Streaming generation using an async generator.
   * Yields incremental StreamChunk objects; the last chunk has done=true.
   *
   * Usage:
   * ```ts
   * for await (const chunk of adapter.stream(options)) {
   *   process.stdout.write(chunk.delta);
   * }
   * ```
   */
  stream(options: GenerateOptions): AsyncGenerator<StreamChunk, void, unknown>;
}

// ─── Provider Registry ────────────────────────────────────────────────────────

export type ProviderName =
  | 'openai'
  | 'ollama'
  | 'anthropic'
  | 'deepseek'
  | 'google'
  | 'mistral'
  | 'meta'
  | 'qwen'
  | 'gemma'
  | 'mock';

// ─── Per-Provider Pricing ─────────────────────────────────────────────────────

/** USD cost per 1 000 prompt/completion tokens, per provider+model. */
export interface ModelPricingEntry {
  /** Cost per 1 000 input (prompt) tokens in USD */
  inputPer1kUsd: number;
  /** Cost per 1 000 output (completion) tokens in USD */
  outputPer1kUsd: number;
}

/**
 * Lookup table: canonical model name → pricing.
 * Partial matches are tried when an exact key is not found.
 */
export const PROVIDER_PRICING: Record<string, ModelPricingEntry> = {
  // ── OpenAI ────────────────────────────────────────────────────────────────
  'gpt-4o':           { inputPer1kUsd: 0.005,    outputPer1kUsd: 0.015   },
  'gpt-4o-mini':      { inputPer1kUsd: 0.00015,  outputPer1kUsd: 0.0006  },
  'gpt-4-turbo':      { inputPer1kUsd: 0.01,     outputPer1kUsd: 0.03    },
  'gpt-3.5-turbo':    { inputPer1kUsd: 0.0005,   outputPer1kUsd: 0.0015  },
  // ── Anthropic ─────────────────────────────────────────────────────────────
  'claude-3-opus':    { inputPer1kUsd: 0.015,    outputPer1kUsd: 0.075   },
  'claude-3-sonnet':  { inputPer1kUsd: 0.003,    outputPer1kUsd: 0.015   },
  'claude-3-haiku':   { inputPer1kUsd: 0.00025,  outputPer1kUsd: 0.00125 },
  'claude-3-5-sonnet':{ inputPer1kUsd: 0.003,    outputPer1kUsd: 0.015   },
  // ── DeepSeek ──────────────────────────────────────────────────────────────
  'deepseek-chat':    { inputPer1kUsd: 0.001,    outputPer1kUsd: 0.002   },
  'deepseek-coder':   { inputPer1kUsd: 0.001,    outputPer1kUsd: 0.002   },
  // ── Google ────────────────────────────────────────────────────────────────
  'gemini-2.0-flash': { inputPer1kUsd: 0.0001,   outputPer1kUsd: 0.0004  },
  'gemini-1.5-pro':   { inputPer1kUsd: 0.0035,   outputPer1kUsd: 0.0105  },
  'gemini-1.5-flash': { inputPer1kUsd: 0.00035,  outputPer1kUsd: 0.00105 },
  // ── Local / Ollama ────────────────────────────────────────────────────────
  'ollama':           { inputPer1kUsd: 0,         outputPer1kUsd: 0       },
  'deepseek-coder:6.7b': { inputPer1kUsd: 0,     outputPer1kUsd: 0       },
};

/**
 * Returns the estimated USD cost for a generation call.
 * Falls back to 0 for unknown / local models.
 */
export function costEstimateUsd(
  model: string,
  promptTokens: number,
  completionTokens: number
): number {
  // Exact match first
  let entry: ModelPricingEntry | undefined = PROVIDER_PRICING[model];

  // Partial match (e.g. "gpt-4o-mini-2024" → "gpt-4o-mini")
  if (!entry) {
    const key = Object.keys(PROVIDER_PRICING).find(
      k => model.toLowerCase().includes(k.toLowerCase())
    );
    entry = key ? PROVIDER_PRICING[key] : undefined;
  }

  if (!entry) return 0;
  return (promptTokens / 1000) * entry.inputPer1kUsd
       + (completionTokens / 1000) * entry.outputPer1kUsd;
}
